import Head from "next/head";
import Banner from "../Components/Banner/Banner";
import Header from "../Components/Header/Header";
import Layout from "../Components/Layout/Layout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Awlad</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Banner />
      </Layout>
    </div>
  );
}
